perf-test-graph-put:
	./ghz --call=pb.GraphService/Put --proto=/Users/skudryashov/dev/go/graphsrv/pkg/pb/graphsrv.proto --insecure --skipTLS --config=./data.json :50051

perf-build:
	go build -o perf perf.go
